Controller
Fallen-Tree/engine pull request #11
Opened 2023-10-18 12:20 UTC by solloball

2023-10-18 12:53 UTC, TheBlek requested changes

2023-10-18 12:53 UTC, TheBlek commented on src/controller/controller.hpp
> +k9 = GLFW_KEY_9,
А почему эти маленькими буквами названы?

2023-10-18 12:53 UTC, TheBlek commented on src/camera/camera.hpp
> +    void update(Input* input, float deltaTime);
Конвенция

2023-10-18 12:53 UTC, TheBlek commented on src/engine.hpp
> +static float s_LastFrame = 0.0f;
Статик переменные в хедере значат немного не то, что нам надо, кажется. Хедеры же просто _копируются_ в то место, где инклюдятся. Соответственно в каждом месте инклюда будет своя копия этой статик переменной. А нам надо, вроде как, чтобы они были только в engine.cpp, или нет?

2023-10-18 12:53 UTC, TheBlek commented on src/engine.cpp
> +#include "controller.hpp"
controller это слишком общее название. Нужно, чтобы название отображало файл. Так ничего не понятно

2023-10-18 12:53 UTC, TheBlek commented on src/controller/controller.cpp
> +}
Давай сделаем здесь все через vec2, чтобы таких соплей не было покомпонентных. Такая переделка нам помешает?

2023-10-18 12:53 UTC, TheBlek commented on src/camera/camera.cpp
> +    if (m_X != input->MouseX() || m_Y != input->MouseY()) {
А зачем нам внутри камеры дублировать слежку за позицией курсора?

2023-10-21 07:09 UTC, TheBlek requested changes

2023-10-21 07:09 UTC, TheBlek commented on src/input/input.hpp
> +    bool IsKeyPressed(key button);
Давай еще добавим различие между IsKeyPressed и IsKeyDown. Чтобы можно было считывать единоразовые события. Думай о прыжках или одиночной стрельбе: если удерживать кнопку, они не будут делаться много раз, а только единожды - при событии нажатия на кнопку

2023-10-21 07:09 UTC, TheBlek commented on src/input/input.hpp
> +Multipy = GLFW_KEY_KP_MULTIPLY,
```suggestion
Multiply = GLFW_KEY_KP_MULTIPLY,
```

2023-10-21 07:09 UTC, TheBlek commented on src/input/input.hpp
> +};  // namespace key
nit: можно таб нажать на всем внутри enum-a

2023-10-21 07:09 UTC, TheBlek commented on src/engine.hpp
> +    Input *m_Input = nullptr;
А почему бы нам не положить здесь просто m_Input, а не указатель?

2023-10-21 07:09 UTC, TheBlek commented on src/engine.cpp
> +// void mouse_callback(GLFWwindow* window, double xpos, double ypos);
Если оно не нужно - можно удалить. Если думаешь, что может понадобиться, то тоже можно удалить - на это есть гит.

2023-10-21 07:09 UTC, TheBlek commented on src/engine.cpp
>  void mouse_callback(GLFWwindow* window, double xposIn, double yposIn) {
Давай удалять мертвый код?

2023-10-21 16:00 UTC, solloball commented on src/input/input.hpp
> +};  // namespace key
не очень понял формулировку

2023-10-24 04:33 UTC, solloball commented on src/input/input.hpp
> +};  // namespace key
@TheBlek

2023-10-24 12:36 UTC, TheBlek requested changes

2023-10-24 12:36 UTC, TheBlek commented on src/input/input.cpp
> +    return glfwGetKey(m_Window, button) == GLFW_RELEASE;
Кажется, мы друг друга не поняли. IsKeyDown - нажата ли кнопка в течении текущего кадра? И оно повторяется. То есть это по-сути наше IsKeyPressed. Хочется, чтобы IsKeyPressed возвращал true, в течении первого кадра нажатия этой кнопки. Тут видимо придется хранить свой массив с текущим состоянием (или предыдущим?) кнопок, потому что glfw не дает такого, насколько я знаю

2023-10-24 12:36 UTC, TheBlek commented on src/engine.cpp
> +    //  glfwSetCursorPosCallback(m_Window, mouse_callback);
Вот это мертвый код, нет?

2023-10-27 15:10 UTC, TheBlek approved these changes

2023-10-30 14:38 UTC, merged