logging commit 1
Fallen-Tree/engine pull request #14
Opened 2023-10-26 03:29 UTC by ZuZKho

2023-10-26 06:20 UTC, TheBlek commented on src/logging/logger.cpp
> +#include <chrono>
@ZuZKho Нам такой линт не нужен. Можешь отключить его? Нужно в CPPLINT.cfg положить -build/c++11

2023-10-26 06:37 UTC, TheBlek requested changes

2023-10-26 06:37 UTC, TheBlek commented on src/logging/logger.cpp
> +    auto milliseconds = nowh.time_since_epoch() / std::chrono::milliseconds(1) % 1000;
Мб переписать вот так: https://stackoverflow.com/a/9089870? Хз насколько читаемей будет

2023-10-26 06:37 UTC, TheBlek commented on src/logging/logger.cpp
> +    tm* tm_local = localtime(&now);
У нас логгинг будет из разных потоков в идеале. Давай здесь использовать безопасный вариант?

2023-10-26 06:37 UTC, TheBlek commented on src/logging/logger.cpp
> +    GetTime();
Может будем buffer локальным делать? Опять таки, чтобы облегчить нам в будущем несколько потоков

2023-10-26 06:37 UTC, TheBlek commented on src/shaders/shader_loader.cpp
> +        Logger::Error("ERROR::SHADER::PROGRAM::LINKING_FAILED %s", infoLog);
Давай ERROR в самом сообщении писать не будем, а подсасывать от уровня логирования

2023-11-01 01:35 UTC, TheBlek commented on src/logging/logger.cpp
> +void Logger::Log(const char* logLevel, const char *format, va_list args) {
Давай logLevel сделаем enum?

2023-11-01 01:35 UTC, TheBlek commented on src/logging/logger.cpp
> +    fprintf(Logger::s_LoggingFile, "%s | %s | ", buffer, logLevel);
Я так понимаю, ты не смотришь на текущий уровень логирования пока?

2023-11-01 01:35 UTC, TheBlek commented on src/engine.cpp
> +            penalty = currentFrame - lastRenderedFrame - (1.f / fpsLimit - penalty);
Какая-то жесть. Что такое пенальти?

2023-11-01 02:18 UTC, ZuZKho commented on src/logging/logger.cpp
> +void Logger::Log(const char* logLevel, const char *format, va_list args) {
Это не тот лог левел который енум. Это текст, который нужно выводить в консоль. Енумовский тоже есть и используется в других местах.

2023-11-01 02:19 UTC, ZuZKho commented on src/logging/logger.cpp
> +    fprintf(Logger::s_LoggingFile, "%s | %s | ", buffer, logLevel);
Смотрю, это внутренний приватный Лог, который вызывается функциями смотрящими на текущие уровни чтобы не повторять код.

2023-11-02 13:34 UTC, TheBlek commented on src/engine.cpp
> +        while (static_cast<int>(floor(static_cast<float>(glfwGetTime()) / frameTime)) != lastRenderedFrame) {
А зачем здесь while? У нас же оно максимум одну итерацию сделает из-за вот этой строчки:
```
lastRenderedFrame = static_cast<int>(floor(static_cast<float>(glfwGetTime()) / frameTime));
```

2023-11-02 13:34 UTC, TheBlek commented on src/engine.cpp
> +        while (static_cast<int>(floor(static_cast<float>(glfwGetTime()) / frameTime)) != lastRenderedFrame) {
И да, почему бы нам не сдвинуть эту часть с Render в конец цикла игрового? Так вроде логичнее выглядит: поситали новый стейт - отрисовали, нет?

2023-11-02 13:34 UTC, TheBlek commented on src/logging/logger.cpp
> +    if (Logger::s_LogLevel == ERROR) return;
Можно будет потом сделать битовую маску какую-нибудь. Пока пофиг, внесу на расмотрение таску

2023-11-10 04:54 UTC, TheBlek approved these changes

2023-11-10 04:54 UTC, TheBlek commented on CMakeLists.txt
> +
А зачем?

2023-11-10 05:04 UTC, TheBlek approved these changes

2023-11-10 05:04 UTC, merged