[GEN-13]Model loader
Fallen-Tree/engine pull request #17
Opened 2023-11-01 04:32 UTC by RomchikkF

2023-11-11 12:57 UTC, solloball requested changes

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +        std::cout << "INCORRECT::FILE::FORMAT::" << fileExtension << std::endl;
здесь логгер стоит использовать

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +        std::cout << "FAILED::TO::OPEN::FILE::" << finalPath << std::endl;
также здесь стоит логгер использовать

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +        if (key == "v") {
может switch..?

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +                        if (indexString != "") {
может switch

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +                    if (verticeString[i] == '/') {
здесь мб через отриц напсать : if (verticeString[i] != '/') {do, continue} и потом без вложенности

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +            // not a valid key at the start of the string
здесь мб ошибку или что то в логгер

2023-11-11 12:57 UTC, solloball commented on src/shaders/shader_loader.cpp
> +//     glDeleteProgram(m_Program);
а зачем нам эти строчки

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +                        }
здесь как будто нужно вывести ошибку, нет?

2023-11-11 12:57 UTC, solloball commented on include/shader_loader.hpp
> +    // ~ShaderProgram();
зачем нам эта строчка

2023-11-11 12:57 UTC, solloball commented on include/model.hpp
> +    static Model* loadFromFile(const char* path);
тут мне кажется стоит вынести loader в отдельный класс, но это мы ещё обсудим

2023-11-11 12:57 UTC, solloball commented on include/model.hpp
> +    static Model* loadFromFile(const char* path);
@TheBlek  что думаешь?

2023-11-11 12:57 UTC, solloball commented on src/model/modelLoader.cpp
> +                // modelVertices.push_back(modelTextures[2 * texturesIndices[i]]);
зачем нам эти строчки?

2023-11-11 12:57 UTC, solloball commented on src/shaders/shader_loader.cpp
> +//     glDeleteProgram(m_Program);
а почему нам не нужно удалять шейдеры  ?

2023-11-12 02:12 UTC, TheBlek commented on include/model.hpp
> +    static Model* loadFromFile(const char* path);
Мне кажется, это пока окей. Потом будем как-нибудь централизировать загрузку ресурсов. Там ведь это задача не только про модели, если так подумать: шейдеры, анимации, потом еще звуки какие-нибудь.

2023-11-12 02:14 UTC, TheBlek commented on src/shaders/shader_loader.cpp
> +//     glDeleteProgram(m_Program);
У нас там бага есть, что этот деструктор постоянно вызывается. Видимо мы где-то в цикле главном копию создаем.  И это такая заплатка получается: шейдер просто не удаляется до завершения приложения.

2023-11-12 02:19 UTC, TheBlek commented on src/model/modelLoader.cpp
> +                        }
Мб ассерт поставить?

2023-11-12 02:20 UTC, TheBlek commented on src/model/model.cpp
> +#include <iostream>
А зачем здесь все эти инклюды?

2023-11-15 03:45 UTC, RomchikkF commented on src/model/modelLoader.cpp
> +        if (key == "v") {
сам хотел написать switch, но он со строками не работает

2023-11-20 02:09 UTC, TheBlek commented
@RomchikkF Тут конфликты с мастером образовались. Померждишь?

2023-11-30 12:20 UTC, TheBlek approved these changes

2023-11-30 13:06 UTC, merged