Texture
Fallen-Tree/engine pull request #19
Opened 2023-11-05 09:34 UTC by solloball

2023-11-09 17:56 UTC, ZuZKho commented on resources/shaders/fragment/red.fshader
> +    FragColor = vec4((ambient + diffuse + specular), 1.0);
![image](https://github.com/Fallen-Tree/engine/assets/106903018/593a6e01-9c51-4317-8bd1-2357d468db7b)
Такое не нужно делать? Освещение уже учитывает все?

2023-11-09 18:04 UTC, ZuZKho commented on src/engine.cpp
> +unsigned int texture1;
Не должна ли текстура принадлежать modelInstance или Object? Если не должна, то почему у нас предел 16 текстур?

2023-11-09 18:09 UTC, ZuZKho commented on src/texture/texture.cpp
> +        std::cout << "Texture failed to load at path: " << finalPath << std::endl;
Не работает, выдает эту ошибку. Texture failed to load at path: C.

2023-11-09 18:15 UTC, ZuZKho commented on src/engine.cpp
> +    texture.loadTexture("/wallspecular.png");
Нормально, что мы храним две картинки по факту принадлежащих к одному объекту в разных текстурах? Учитывются ли при рендере оба изображения?

2023-11-09 18:17 UTC, ZuZKho reviewed
В основном вопросы чтобы мне понятнее стало.

2023-11-10 02:45 UTC, TheBlek commented on include/texture.hpp
> +    void loadTexture(std::string path);
Мне кажется тут страдает терминология немного. Текстуры != картинки (карты?). Поэтому вот эти loadTexture делают неочевидные вещи

2023-11-11 06:28 UTC, TheBlek requested changes

2023-11-11 06:28 UTC, TheBlek commented on resources/shaders/fragment/red.fshader
>      vec3 ambient;
А нам все еще нужен ambient для материала? В этом шейдере он вроде не используется

2023-11-11 06:28 UTC, TheBlek commented on src/engine.cpp
> +    Model * testModel = new Model(cubeVertices, 3);
А почему 3, а не 8?

2023-11-11 06:28 UTC, TheBlek commented on src/engine.cpp
> +    Model * testModel = new Model(cubeVertices, 3);
А почему 3, а не 8?

2023-11-11 06:28 UTC, TheBlek commented on src/engine.cpp
> +    Model * testModel = new Model(cubeVertices, 3);
Вроде сюда надо размер одной вершины писать, да? Тут оно 8, нет?

2023-11-11 06:28 UTC, TheBlek commented on src/texture/texture.cpp
> +        std::cout << "index out of bounds" << std::endl;
Давай на логгер переделаем, чтобы все было в едином стиле?

2023-11-11 06:28 UTC, TheBlek commented on src/texture/texture.cpp
> +        std::cout << "failed to load texture at path" << path
Вот тут тоже можно на логгер переделать. Тогда и зависимость на iostream не нужна будет (вроде)

2023-11-11 08:55 UTC, solloball commented on src/engine.cpp
> +    Model * testModel = new Model(cubeVertices, 3);
Здесь я тестил с разными значениями и забыл убрать(

2023-11-11 09:00 UTC, solloball commented on resources/shaders/fragment/red.fshader
>      vec3 ambient;
@TheBlek я ещё удалил с материалов остальные компоненты, остались только m_Shininess

2023-11-12 02:10 UTC, TheBlek commented on src/texture/texture.cpp
> +        std::cout << "index out of bounds" << std::endl;
Подожди, а зачем оставлять std::cout?

2023-11-12 02:21 UTC, TheBlek commented on src/texture/texture.cpp
> +        std::cout << "index out of bounds" << std::endl;
@solloball

2023-11-12 11:53 UTC, TheBlek approved these changes

2023-11-12 13:23 UTC, merged