GEN-68 Update shader methods
Fallen-Tree/engine pull request #25
Opened 2023-11-14 19:05 UTC by RomchikkF

2023-11-17 02:37 UTC, TheBlek requested changes

2023-11-17 02:37 UTC, TheBlek commented on src/engine.cpp
> +    testModel->shader = &shaderProgram;
Тут ссылка на память в стеке будет, UB. Ссылка переживет память скорее всего

2023-11-17 02:37 UTC, TheBlek commented on src/engine.cpp
> +    testModel->shader = &shaderProgram;
Мб сделать shared_pointer в этот шейдер, чтобы он освобождался правильно?

2023-11-17 03:31 UTC, TheBlek commented on src/engine.cpp
> +    testModel->shader = &shaderProgram;
https://www.youtube.com/watch?v=UOB7-B2MfwA

2023-11-24 03:59 UTC, solloball submitted a review, later dismissed

2023-11-29 03:40 UTC, TheBlek approved these changes

2023-11-29 03:40 UTC, merged