constants
Fallen-Tree/engine pull request #29
Opened 2023-11-22 03:07 UTC by ZuZKho

2023-11-22 13:55 UTC, solloball requested changes

2023-11-22 13:55 UTC, solloball commented on include/texture.hpp
> +    unsigned int m_TextureId[MAXCOUNTTEXTURE];
а почему данная константа не в config.hpp ?

2023-11-22 13:55 UTC, solloball commented on include/user_config.hpp
> +#define SENSIVITY 0.1f
https://habr.com/ru/articles/228181/ дефайн это штука не для плюсов

2023-11-22 13:55 UTC, solloball commented on include/user_config.hpp
> +#define SENSIVITY 0.1f
тебе стоит использовать constexpr, в таске написано

2023-11-22 13:55 UTC, solloball commented on include/camera.hpp
> +const float PITCH       =  DFL_PITCH;
а зачем

2023-11-22 13:55 UTC, solloball commented on include/camera.hpp
> +const float SPEED       =  2.5f; // One day we will change camera speed
а почему она определена здесь, смысл таски вроде был констатнты в одном месте хранить

2023-11-24 02:26 UTC, ZuZKho commented on include/texture.hpp
> +    unsigned int m_TextureId[MAXCOUNTTEXTURE];
А где она?

2023-11-24 02:28 UTC, ZuZKho commented on include/user_config.hpp
> +#define SENSIVITY 0.1f
Зачем constexpr если я ничего не вычисляю

2023-11-24 03:08 UTC, TheBlek submitted a review, later dismissed

2023-11-28 07:41 UTC, solloball approved these changes

2023-11-28 08:53 UTC, merged