[GEN-63] Extract object
Fallen-Tree/engine pull request #30
Opened 2023-11-22 05:23 UTC by solloball

2023-11-22 05:57 UTC, solloball commented on src/engine.cpp
> +Engine::Engine(int SCR_WIDTH, int SCR_HEIGHT) {
Здесь создаётся окно, потому что иначе gladLoadGLLoader фейлится, потому что glfwGetProcAddress нужен контекст, который не создаётся без создания окна: https://stackoverflow.com/questions/48650497/glad-failing-to-initialize

2023-11-22 09:56 UTC, TheBlek requested changes

2023-11-22 09:56 UTC, TheBlek commented on src/engine.cpp
> +        glDeleteVertexArrays(1, &m_Objects[i]->renderData->VAO);
Не у всех объектов будут renderData. Тут по null-у можешь сходить

2023-11-22 09:56 UTC, TheBlek commented on src/engine.cpp
> +        ShaderProgram* shader = model->shader;
Почему бы здесь не использовать референс? Тогда не придется менять так много строк ниже
https://www.youtube.com/watch?v=IzoFn3dfsPA

2023-11-22 09:56 UTC, TheBlek commented on src/main.cpp
> +    glGenVertexArrays(1, &render_data->VAO);
По-хорошему надо унести всю эту фигню с OpenGL в RenderData (Или еще куда-нибудь). Таким пользователи по-идее не должны заниматься

2023-11-29 03:53 UTC, TheBlek submitted a review, later dismissed

2023-11-29 08:32 UTC, merged