[GEN-62] Adding GetResourcePath mechanics
Fallen-Tree/engine pull request #39
Opened 2024-02-13 19:04 UTC by ZuZKho

not fully ready

2024-02-14 04:44 UTC, TheBlek requested changes

2024-02-14 04:44 UTC, TheBlek commented on src/main.cpp
> +const char *vertexShaderSource = "/standart.vshader";
Давай сделаем так, чтобы первый слеш не был нужен в пути

2024-02-14 04:44 UTC, TheBlek commented on src/main.cpp
> +    Shader vShader = Shader(VertexShader, GetResourcePath(Resource::VSHADER, vertexShaderSource));
Давай GetResourcePath под капот спрячем. А то получается не очень удобно создавать ресурсы

2024-02-19 04:04 UTC, ZuZKho commented on src/main.cpp
> +const char *vertexShaderSource = "/standart.vshader";
Можно как со слешем, так и без него

2024-02-19 13:31 UTC, TheBlek approved these changes

2024-02-20 12:17 UTC, merged