Instance
Fallen-Tree/engine pull request #5
Opened 2023-10-04 11:20 UTC by solloball

2023-10-04 13:29 UTC, TheBlek requested changes

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.cpp
> +    makeTransform();
Зачем здесь пересчитывать матрицу преобразования?

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.cpp
> +Transformation::Transformation
Это не преобразование. Преобразование, это если ты упакуешь все тоже самое, только без модели. (+ Имя можно сократить до Transform, как ты сделал для переменной).
В текущем виде это скорее ModelInstance или просто Instance

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.hpp
> +    glm::vec3 rotate;
Может быть передать смысл переменной в названии, а не в комментарии? На ум приходит что-нибудь типо axis, или rotation_axis

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.cpp
> +void Transformation::setRotate(glm::vec3 rotate, float angle) {
Rotate это глагол. Просто как-то не естественно выглядит. Может быть Rotation?

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.cpp
> +void Transformation::setRotate(glm::vec3 rotate, float angle) {
Тут тоже rotate название для переменной ни о чем не говорит

2023-10-04 13:29 UTC, TheBlek commented on src/model/transformation.hpp
> +#include <glm/glm.hpp>
У меня на компьютере это не инклюдится. Может CMakeLists не закоммитился?

2023-10-04 16:22 UTC, ZuZKho commented on src/model/transformation.cpp
> +}
Тут нужно быть осторожным с порядком применения функций rotate, scale, translate. В лекциях на этом заостряли внимание. Помоему Translate точно должен быть первым, а вот дальше надо почитать. Думаю Translate, rotate, scale.

2023-10-07 17:07 UTC, ZuZKho approved these changes

2023-10-07 17:13 UTC, merged