[GEN-135] Realistic rotation
Fallen-Tree/engine pull request #54
Opened 2024-03-20 02:03 UTC by solloball

2024-03-25 04:40 UTC, TheBlek approved these changes

2024-03-26 13:14 UTC, ZuZKho requested changes
При большом fps все стоит на месте, при маленьком катается, но объекты сильно входят друг в друга.

2024-03-27 02:56 UTC, TheBlek commented on src/components/rigid_body.cpp
> +        m_Torque = Vec3(0);
Может если трение слишком большое надо не полностью останавливать повороты, а как бы применять нулевую силу? Чтобы поврот естественным образом затухал

2024-03-27 03:19 UTC, solloball commented on src/components/rigid_body.cpp
> +        m_Torque = Vec3(0);
Поставил LimitTorque вместо этой строчки

2024-03-31 11:23 UTC, TheBlek submitted a review, later dismissed
LGTM

2024-04-01 02:55 UTC, TheBlek approved these changes

2024-04-01 04:50 UTC, ZuZKho approved these changes

2024-04-01 04:56 UTC, merged