Objects names
Fallen-Tree/engine pull request #71
Opened 2024-04-23 14:10 UTC by ZuZKho

2024-04-23 14:36 UTC, ZuZKho commented on src/engine.cpp
> +void Engine::SetObjectName(ObjectHandle handle, std::string name) {
Если эту функцию случайно позовет юзер, то все сломается, т.к. она не меняет m_Name в самом Object. Пока не знаю как это решать. Единственная идея хранить ComponentArray m_Objects

2024-04-24 01:38 UTC, TheBlek requested changes

2024-04-24 01:38 UTC, TheBlek commented on src/object.cpp
> +    return m_Name;
В таком виде объект может не заметить, что его имя поменяли в движке через другой референс (объект)

2024-04-24 01:38 UTC, TheBlek commented on include/engine.hpp
> +    std::map<std::string, std::set<int> > m_ActiveObjects;
Тут по-хорошему надо ObjectHandle хранить

2024-04-24 01:38 UTC, TheBlek commented on src/engine.cpp
> +    ObjectHandle handle = *m_AvailableObjectIds.begin();
С этим могут быть проблемы (В зависимости от того, куда вставляет элементы сет). Пример: создается объект с индексом n; Создается два референса на объект n; Референс №1 удаляет объект с индексом n; Создается новый объект с индексом n; Референс №2 теперь честно думает, что показывает на адекватный объект, хотя это совсем не так.
Такое может и не происходить: мы вроде не создаем объекты динамически. Но если уж мы и не создаем объекты динамически я не вижу смысла в нагромаждении, которое будет ухудшать наши начавшиеся проблемы с производительностью.

2024-04-24 01:38 UTC, TheBlek commented on src/engine.cpp
> +void Engine::SetObjectName(ObjectHandle handle, std::string name) {
Не надо m_Objects никакого. Просто каждый объект будет ходить в движок, чтобы узнать своё имя. В текущем варианте есть ещё и баг см. комментарий на файл object.cpp

2024-04-29 14:14 UTC, TheBlek approved these changes

2024-05-02 05:59 UTC, merged